version: '3.8'

services:
    purge-aws-task:
        env_file: .env
        image: ghcr.io/jpbarto/purge-aws
        # x-aws-policies:
        #     - arn:aws:iam::aws:policy/AdministratorAccess
        platform: linux/amd64
